$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
$payloadDirectory = Join-Path $projectRoot "release\payload"

$markerPath = Join-Path $payloadDirectory ".valorant-custom-bot-payload"
if (Test-Path -LiteralPath $payloadDirectory) {
  if (!(Test-Path -LiteralPath $markerPath)) {
    $requiredFiles = @("dist\index.js", "assets\maps", "package.json", "package-lock.json", "node.exe")
    foreach ($relativePath in $requiredFiles) {
      if (!(Test-Path -LiteralPath (Join-Path $payloadDirectory $relativePath))) {
        throw "既存の配布先がこのスクリプトの出力と確認できません。手動で確認してください: $payloadDirectory"
      }
    }
    Set-Content -LiteralPath $markerPath -Value "Generated by scripts/package-windows.ps1" -Encoding ascii
  }
} else {
  New-Item -ItemType Directory -Path $payloadDirectory -Force | Out-Null
  Set-Content -LiteralPath $markerPath -Value "Generated by scripts/package-windows.ps1" -Encoding ascii
}

Push-Location $projectRoot
try {
  npm.cmd run build
  if ($LASTEXITCODE -ne 0) { throw "TypeScriptのビルドに失敗しました。" }
} finally {
  Pop-Location
}

foreach ($name in @("dist", "assets")) {
  $sourceDirectory = Join-Path $projectRoot $name
  $targetDirectory = Join-Path $payloadDirectory $name
  New-Item -ItemType Directory -Path $targetDirectory -Force | Out-Null
  Copy-Item -Path (Join-Path $sourceDirectory "*") -Destination $targetDirectory -Recurse -Force
}
Copy-Item -LiteralPath (Join-Path $projectRoot "package.json") -Destination $payloadDirectory -Force
Copy-Item -LiteralPath (Join-Path $projectRoot "package-lock.json") -Destination $payloadDirectory -Force

$nodeCommand = Get-Command node -ErrorAction Stop
Copy-Item -LiteralPath $nodeCommand.Source -Destination (Join-Path $payloadDirectory "node.exe") -Force

$launcherScript = @(
  "@echo off",
  "setlocal",
  'cd /d "%~dp0"',
  'if /i "%~1"=="shell" (',
  "  node.exe dist\cli.js help",
  "  echo.",
  "  cmd.exe /K",
  "  exit /b",
  ")",
  'if "%~1"=="" (',
  "  node.exe dist\cli.js help",
  "  exit /b 1",
  ")",
  'node.exe dist\cli.js "%~1"',
  "exit /b %errorlevel%"
) -join "`r`n"
[IO.File]::WriteAllText((Join-Path $payloadDirectory "vbot.cmd"), "$launcherScript`r`n", (New-Object System.Text.UTF8Encoding($false)))
foreach ($legacyLauncher in @("start-bot.cmd", "setup-bot.cmd", "register-commands.cmd")) {
  $legacyPath = Join-Path $payloadDirectory $legacyLauncher
  if (Test-Path -LiteralPath $legacyPath -PathType Leaf) { Remove-Item -LiteralPath $legacyPath }
}
Push-Location $payloadDirectory
try {
  npm.cmd ci --omit=dev --ignore-scripts
  if ($LASTEXITCODE -ne 0) { throw "本番依存パッケージの準備に失敗しました。" }
  $sqlitePrebuilt = Join-Path $payloadDirectory "node_modules\better-sqlite3\prebuilds\win32-x64.node"
  if (!(Test-Path -LiteralPath $sqlitePrebuilt)) { throw "better-sqlite3のWindows x64同梱バイナリが見つかりません: $sqlitePrebuilt" }
} finally {
  Pop-Location
}

Write-Host "配布用ファイルを作成しました: $payloadDirectory"
Write-Host "次は Inno Setup Compiler で installer\ValorantCustomBot.iss をコンパイルしてください。"